### ISSUE TITLE
Módulo NFSe

### ISSUE THREAD

**Issue by marceloengecom** [proge/l10n_br_nfse#1]
Boa noite,

Estou estudando o OpenERP/Odoo de forma mais aprofundada desde o início do ano e um dos seus problemas é a não emissão de nota fiscal de serviços eletrônica. 

Gostaria de saber se esse módulo (l10n_br_nfse) , desenvolvido pela Proge, é funcional e se é possível adaptá-lo para a versão 8 do Odoo?

Sou de Porto Alegre e meu interesse é disponibilizar o Odoo para meus clientes, que em sua maioria, são fornecedores de serviços.

Atensiosamente,
Marcelo Costa

**Comment by daniel-hartmann** [comment]
Boa tarde,

Esse módulo é antigo e não está sendo mantido. Mas com certeza você pode usá-lo e adaptá-lo pra versão 8.

Abraço,
Daniel

**Comment by marceloengecom** [comment]
Ok Daniel,

Obrigado pela resposta.
